//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using WinSvcTaskTimer.Core;
namespace WinSvcTaskTimer.Configuration
{
    public sealed class TaskHost
    {

        private static TaskHostSection _config;

        static TaskHost()
        {
            _config = ((TaskHostSection)(global::System.Configuration.ConfigurationManager.GetSection("TaskHost")));
        }

        private TaskHost()
        {
        }

        public static TaskHostSection Config
        {
            get
            {
                return _config;
            }
        }
    }

    public sealed partial class TaskHostSection : System.Configuration.ConfigurationSection
    {

        [System.Configuration.ConfigurationPropertyAttribute("Tasks")]
        [System.Configuration.ConfigurationCollectionAttribute(typeof(TasksElementCollection.TaskElement), AddItemName = "Task")]
        public TasksElementCollection Tasks
        {
            get
            {
                return ((TasksElementCollection)(this["Tasks"]));
            }
        }

        [System.Configuration.ConfigurationPropertyAttribute("Timers")]
        [System.Configuration.ConfigurationCollectionAttribute(typeof(TimersElementCollection.TimerElement), AddItemName = "Timer")]
        public TimersElementCollection Timers
        {
            get
            {
                return ((TimersElementCollection)(this["Timers"]));
            }
        }

        public sealed partial class TasksElementCollection : System.Configuration.ConfigurationElementCollection
        {

            public TaskElement this[int i]
            {
                get
                {
                    return ((TaskElement)(this.BaseGet(i)));
                }
            }

            protected override System.Configuration.ConfigurationElement CreateNewElement()
            {
                return new TaskElement();
            }

            protected override object GetElementKey(System.Configuration.ConfigurationElement element)
            {
                return ((TaskElement)(element)).Name;
            }

            public sealed partial class TaskElement : System.Configuration.ConfigurationElement
            {

                [System.Configuration.ConfigurationPropertyAttribute("Name", IsRequired = true)]
                public string Name
                {
                    get
                    {
                        return ((string)(this["Name"]));
                    }
                    set
                    {
                        this["Name"] = value;
                    }
                }

                [System.Configuration.ConfigurationPropertyAttribute("Type", IsRequired = true)]
                public string Type
                {
                    get
                    {
                        return ((string)(this["Type"]));
                    }
                    set
                    {
                        this["Type"] = value;
                    }
                }

                [System.Configuration.ConfigurationPropertyAttribute("Argument", IsRequired = false)]
                public string Argument
                {
                    get
                    {
                        return ((string)(this["Argument"]));
                    }
                    set
                    {
                        this["Argument"] = value;
                    }
                }

                [System.Configuration.ConfigurationPropertyAttribute("Method", IsRequired = false, DefaultValue = "Run")]
                public string Method
                {
                    get
                    {
                        return ((string)(this["Method"])) ?? "Run";
                    }
                    set
                    {
                        this["Method"] = value;
                    }
                }
            }
        }

        public sealed partial class TimersElementCollection : System.Configuration.ConfigurationElementCollection
        {

            public TimerElement this[int i]
            {
                get
                {
                    return ((TimerElement)(this.BaseGet(i)));
                }
            }

            protected override System.Configuration.ConfigurationElement CreateNewElement()
            {
                return new TimerElement();
            }

            protected override object GetElementKey(System.Configuration.ConfigurationElement element)
            {
                return ((TimerElement)(element)).Name;
            }

            public sealed partial class TimerElement : System.Configuration.ConfigurationElement
            {

                [System.Configuration.ConfigurationPropertyAttribute("Name", IsRequired = true)]
                public string Name
                {
                    get
                    {
                        return ((string)(this["Name"]));
                    }
                    set
                    {
                        this["Name"] = value;
                    }
                }

                [System.Configuration.ConfigurationPropertyAttribute("TaskName", IsRequired = true)]
                public string TaskName
                {
                    get
                    {
                        return ((string)(this["TaskName"]));
                    }
                    set
                    {
                        this["TaskName"] = value;
                    }
                }

                [System.Configuration.ConfigurationPropertyAttribute("Interval", IsRequired = true)]
                public System.TimeSpan Interval
                {
                    get
                    {
                        return ((System.TimeSpan)(this["Interval"]));
                    }
                    set
                    {
                        this["Interval"] = value;
                    }
                }

                [System.Configuration.ConfigurationPropertyAttribute("Delay", IsRequired = true)]
                public System.TimeSpan Delay
                {
                    get
                    {
                        return ((System.TimeSpan)(this["Delay"]));
                    }
                    set
                    {
                        this["Delay"] = value;
                    }
                }

                [System.Configuration.ConfigurationPropertyAttribute("TickBehavior", IsRequired = true)]
                public TimerTickBehavior TickBehavior
                {
                    get
                    {
                        return ((TimerTickBehavior)(this["TickBehavior"]));
                    }
                    set
                    {
                        this["TickBehavior"] = value;
                    }
                }

                [System.Configuration.ConfigurationPropertyAttribute("Enabled", IsRequired = true)]
                public bool Enabled
                {
                    get
                    {
                        return ((bool)(this["Enabled"]));
                    }
                    set
                    {
                        this["Enabled"] = value;
                    }
                }
            }
        }
    }
}
